# -*- coding: utf-8 -*-
"""data analysis(practice)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BR1wqin_6kRdwqK2LZWBWTpOB3T1EMBF

# project1 
#Project - 1 (Case Study - 1) | Data Analysis With Python Pandas | E-Commerce Purchases Dataset
"""

import pandas as pd

data = pd.read_csv("/content/Ecommerce Purchases")
print(data)

#DISPLAY TOP 10 ROWS OF DATASET (Q1) #note head method without arg prints top 5 by default
data.head(10)

#CHECK LAST 10 ROWS (Q2)
data.tail(10)

#CHECK DATATYPE OF EACH COLUMN (Q3)
data.dtypes

#CHECK NULL VALUES IN THE DATASET (Q4)
data.isna().sum()

#HOW MANY ROWS AND COLUMNS ARE THERE IN OUR DATASET? (Q5)
v=list(data.shape)
print("how many rows : "+str(v[0]))
print("how many column : "+str(v[1]))

data.info

v=len(data.columns)
v1=len(data)
print(v,v1)

#HIGHEST AND LOWEST PURCHASE PRICES (Q6)
data.columns

data['Purchase Price'].max() #higest price

data['Purchase Price'].min() #lowest price

#AVERAGE PURCHASE PRICE (Q7)
data['Purchase Price'].mean()

#HOW MANY PEOPLE HAVE FRENCH AS THEIR LANGUAGE (Q8)
#NOTE FRENCH = fr IN THE DATA
len(data[data['Language']=='fr']) #1st way

data[data['Language']=='fr'].count() #2nd way

#JOB TITLE CONTAINING ENGINEER (Q9)
data.columns

len(data[data['Job'].str.contains('engineer')]) #by default it contains case sensitives
len(data[data['Job'].str.contains('engineer',case=False)]) #includes case sensitives also

#FIND EMAIL OF PERSON WITH FOLLOWING IP 132.207.160.22 (Q10)
data.columns

data[data['IP Address']=='132.207.160.22']['Email']

#How many People have Mastercard as their Credit Card Provider and made a purchase above 50 (Q11)
data.columns

len(data[(data['CC Provider']=='Mastercard') & (data['Purchase Price']>50)])

#Find the email of the person with the following Credit Card Number: 4664825258997302 (Q12)
data.columns

data[data['Credit Card']==4664825258997302]['Email']

#How many people purchase during the AM and how many people purchase during PM
data.columns

v=len(data[data['AM or PM']=='AM'])
v1=len(data[data['AM or PM']=='PM'])
print("AM {} and PM {}".format(v,v1))

data['AM or PM'].value_counts()

#How many people have a credit card that expires in 2020?
data.columns

data['CC Exp Date']

def spl():
  c=0
  for i in data['CC Exp Date']:
    if i.split('/')[1]=='20':
      c+=1
  print(c)
spl()

#data[data['CC Exp Date']].apply(lambda x:x[3:]=='20')

#What are the top 5 most popular email providers (e.g. gmail.com, yahoo.com, etc...) (Q15)
data.columns

l=[]
for i in data['Email']:
  v=i.split("@")
  #print(v[1])
  l.append(v[1])
data['pro']=l
data['pro'].value_counts().head()

data['Email'].apply(lambda x:x.split('@')[1]).value_counts().head()

"""# Project - 2 (Case Study - 2) | Data Analysis With Python Pandas | Kaggle Dataset"""

